name: Deploy static content to GH Pages

on:
  workflow_dispatch:
    inputs:
      destination_dir:
        description: 'Version number x.x.x'
        required: true
        type: string

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Ensure destination folder is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
      - name: Build static files
        env:
          VITE_VERSION: ${{ inputs.destination_dir }}
        run: yarn build
      - name: Deploy to `${{ inputs.destination_dir }}` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ inputs.destination_dir }}
